name: "Test action-amazon-chime"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'
      # Greenkeeper provides automated dependency management
      # for this repository. It will automatically create
      # new branches with updated npm versions, and send
      # PRs for those automatically, if they build.
      # Greenkeeper relies on this CI to determine if a
      # PR needs to be open or not, and as such we need
      # to whitelist those branches for CI run here.
      # See also https://greenkeeper.io/faq#no-initial-pr
      - 'greenkeeper**'

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1

    - run: npm ci
    - run: npm run build

    - uses: ./ # Uses an action in the root directory
      with:
        message: |
          [${{ github.workflow }}][${{ github.event_name }}] :white_check_mark: Test message sent by the action-amazon-chime e2e test.
          Link to GitHub Action run: https://github.com/${{ github.repository }}/commit/${{ github.sha }}/checks
        # Webhook URL to the chat room called "Test Room".
        webhook: ${{ secrets.testRoomWebHookUrl }}
